server.port=${PORT:8080}
spring.application.name=inventarios

# Forzamos a que use el Driver de MySQL y el Dialecto de MySQL 8
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Variables de conexión
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Configuración Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.main.banner-mode=off

# Logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Mailtrap (asegúrate de que las variables existan en Render)
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=${MAIL_USER}
spring.mail.password=${MAIL_PASS}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
# <--- AQUÍ TERMINA EL ARCHIVO, sin líneas extra