spring.application.name=inventarios
# Conexion mysql
spring.datasource.url=jdbc:mysql://mysql-1e74f8e0-rafatorretta-61b4.e.aivencloud.com:26012/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
# Evitar que se cree el esquema de bd
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# banner
spring.main.banner-mode=off
# Configuracion del logging en consola
logging.pattern.console=[%thread] %-5level: %logger - %msg%n
logging.level.root=INFO

# CONFIGURACION DE SPRING MAIL
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=${MAIL_USER}
spring.mail.password=${MAIL_PASS}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
