server.port=${PORT:8080}
spring.application.name=inventarios

# Configuración de Base de Datos
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/inventario_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Stardust3951.}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.main.banner-mode=off

# Logging
logging.pattern.console=[%thread] %-5level: %logger - %msg%n
logging.level.root=INFO

# Configuración Mailtrap
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=${MAIL_USER}
spring.mail.password=${MAIL_PASS}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true